#!/usr/bin/env python

# This is only needed for Python v2 but is harmless for Python v3.
# import sip
# sip.setapi('QString', 2)

from PySide import QtCore, QtGui, QtSvg
import svg
import math

import engine
import heatmap

class MainWindow(QtGui.QMainWindow):
    AUTO_MODE = 0
    MANUAL_MODE = 1
    def __init__(self):
        super(MainWindow, self).__init__()

        self.currentPath = ''

        self.view = SvgView()
        self.manualView = ManualView()

        # File menu
        fileMenu = QtGui.QMenu("&File", self)
        openAction = fileMenu.addAction("&Open...")
        openAction.setShortcut("Ctrl+O")
        quitAction = fileMenu.addAction("E&xit")
        quitAction.setShortcut("Ctrl+Q")

        openAction.triggered.connect(self.openFile)
        quitAction.triggered.connect(QtGui.qApp.quit)

        self.menuBar().addMenu(fileMenu)

        # View menu
        viewMenu = QtGui.QMenu("&View", self)
        self.backgroundAction = viewMenu.addAction("&Background")
        self.backgroundAction.setEnabled(False)
        self.backgroundAction.setCheckable(True)
        self.backgroundAction.setChecked(False)
        self.backgroundAction.toggled.connect(self.view.setViewBackground)

        self.outlineAction = viewMenu.addAction("&Outline")
        self.outlineAction.setEnabled(False)
        self.outlineAction.setCheckable(True)
        self.outlineAction.setChecked(True)
        self.outlineAction.toggled.connect(self.view.setViewOutline)

        self.menuBar().addMenu(viewMenu)

        # Mode menu
        modeMenu = QtGui.QMenu("&Mode", self)

        manualAction = modeMenu.addAction("M&anual")
        manualAction.setShortcut("Ctrl+M")
        manualAction.triggered.connect(self.manualMode)

        automaticAction = modeMenu.addAction("A&utomatic")
        automaticAction.setShortcut("Ctrl+A")
        automaticAction.triggered.connect(self.automaticMode)

        self.menuBar().addMenu(modeMenu)

        self.automaticMode()

    def manualMode(self):
        self.setCentralWidget(self.manualView)
        self.view = SvgView()
        self.setWindowTitle("Carosif - Manual mode")

    def automaticMode(self):
        self.setCentralWidget(self.view)
        self.manualView = SvgView()
        self.setWindowTitle("Carosif - Automatic mode")

    def openFile(self, path=None):
        if not path:
            path = QtGui.QFileDialog.getOpenFileName(self, "Open SVG File", self.currentPath, "SVG files (*.svg *.svgz *.svg.gz)")[0]
        if path:
            svg_file = QtCore.QFile(path)
            if not svg_file.exists():
                QtGui.QMessageBox.critical(self, "Open SVG File",
                        "Could not open file '%s'." % path)

                self.outlineAction.setEnabled(False)
                self.backgroundAction.setEnabled(False)
                return

            self.view.openFile(svg_file)
            if not path.startswith(':/'):
                self.currentPath = path
                self.setWindowTitle("Carosif - Automatic mode - Map : {}".format(self.currentPath))
            self.outlineAction.setEnabled(False)
            self.backgroundAction.setEnabled(True)

            self.resize(self.view.sizeHint() + QtCore.QSize(80, 80 + self.menuBar().height()))

            #self.svg = pysvg.parser.parse('mapexample.svg')

class ManualView(QtGui.QGraphicsView):

    def __init__(self, parent=None):
        super(ManualView, self).__init__(parent)

        self.setRenderHints(QtGui.QPainter.Antialiasing | QtGui.QPainter.SmoothPixmapTransform)

        self.setScene(ManualScene(self))

        tilePixmap = QtGui.QPixmap(64, 64)
        tilePixmap.fill(QtGui.QColor(230, 230, 230))
        self.setBackgroundBrush(QtGui.QBrush(tilePixmap))

    def paintEvent(self, event):
        super(ManualView, self).paintEvent(event)

class ManualScene(QtGui.QGraphicsScene):
    def __init__(self, parent=None):
        super(ManualScene, self).__init__(parent)
        self.car = engine.Car()
        self.addItem(self.car)

    def mousePressEvent(self, event):
        x, y = event.scenePos().x(), event.scenePos().y()

        super(ManualScene,self).mousePressEvent(event)

    def mouseMoveEvent(self, event):
        x, y = event.scenePos().x(), event.scenePos().y()
        super(ManualScene,self).mouseMoveEvent(event)

class ViewerScene(QtGui.QGraphicsScene):
    def __init__(self, parent=None):
        super(ViewerScene, self).__init__(parent)
        #self.setDragMode(QtGui.QGraphicsScene.ScrollHandDrag)

        self.x = 0
        self.y =0

        # Car object (model + graphics informations)
        self.car = None

        # Map generated by parsing an svg file
        self.map = None

        # The last generated path
        self.path = None

        # Graphical representation of the last generated path
        self.graphicPath = None

        # Not used (as of 29/03), should be a graphic item for the car's "ray"
        self.ray = None

        # Heatmap, should be used for probabilities [WIP]
        self.heatmap = None
        self.graphicalHeatmap = None
        # ( initialized when pressing 'H' )

    def mousePressEvent(self, event):
        x, y = event.scenePos().x(), event.scenePos().y()

        # If the car doesn't exist yet, we place it where we clicked
        if not self.car:
            self.car = engine.Car(self.map, x, y)
            self.addItem(self.car)

            #Fade in animation
            self.animation = QtCore.QPropertyAnimation(self.car, "opacity")
            self.animation.setDuration(700)
            self.animation.setStartValue( 0.0 )
            self.animation.setEndValue( 1.0 )
            self.animation.start( QtCore.QAbstractAnimation.DeleteWhenStopped )

        # If the car already exists, we generate a path from the car to where we clicked
        # and show it on the UI
        else:
            #We get the path from our 'map' object
            self.path = self.map.search((self.car.x(), self.car.y()), (x,y))

            if len(self.path) > 0:
                # We build a polyline graphic item
                painterPath = QtGui.QPainterPath()
                painterPath.moveTo(self.path[0].x, self.path[0].y)
                for i in range(1, len(self.path)):
                    painterPath.lineTo(self.path[i].x, self.path[i].y)

                # If a path is already shown on screen, we just update it with the new path
                if self.graphicPath is not None:
                    self.graphicPath.setPath(painterPath)
                # Else, we create a new graphical path
                else:
                    self.graphicPath = QtGui.QGraphicsPathItem(painterPath)
                    self.addItem( self.graphicPath )

                # Animating the car on the path
                self.animation = QtCore.QSequentialAnimationGroup();

                speed = 20
                for i in range(1, len(self.path)):
                    lastPoint = self.path[i-1]
                    point = self.path[i]
                    distance = math.sqrt( (lastPoint.x - point.x)**2 + (lastPoint.y - point.y)**2 )

                    anim = QtCore.QPropertyAnimation(self.car, "pos")
                    anim.setDuration(100*(distance/speed))
                    anim.setStartValue( QtCore.QPointF(lastPoint.x, lastPoint.y) )
                    anim.setEndValue( QtCore.QPointF(point.x, point.y) )
                    self.animation.addAnimation(anim)

                self.animation.start(QtCore.QAbstractAnimation.DeleteWhenStopped)

        super(ViewerScene,self).mousePressEvent(event)

    def mouseMoveEvent(self, event):
        x, y = event.scenePos().x(), event.scenePos().y()

        if self.car:
            #We calculate the angle (in radians) and convert it to the trigonometric referential
            angle = math.pi - math.atan2(self.car.y() - y, self.car.x() - x)

            if angle > math.pi:
                angle = angle - 2*math.pi

            self.car.rotate(angle)

    def keyPressEvent(self, event):

        # Moving the car
        speed = 20
        if self.car:
            if event.key()==QtCore.Qt.Key_Up or event.key()==QtCore.Qt.Key_Z:
                self.car.move(speed)
            elif event.key()==QtCore.Qt.Key_Down or event.key()==QtCore.Qt.Key_S:
                self.car.move(-speed)

        # Heatmap
        if event.key() == QtCore.Qt.Key_H:
            self.heatmap = heatmap.Heatmap( self.map.width / 4 ,  self.map.height / 4)
            self.graphicalHeatmap = heatmap.GraphicalHeatmap(self.heatmap, self.map.width, self.map.height)
            self.graphicalHeatmap.setZValue(-1)
            self.addItem( self.graphicalHeatmap )

class SvgView(QtGui.QGraphicsView):
    Native, OpenGL, Image = range(3)

    def __init__(self, parent=None):
        super(SvgView, self).__init__(parent)

        self.setRenderHints(QtGui.QPainter.Antialiasing | QtGui.QPainter.SmoothPixmapTransform)

        self.renderer = SvgView.Native
        self.svgItem = None
        self.backgroundItem = None
        self.outlineItem = None
        self.image = QtGui.QImage()

        self.setScene(ViewerScene(self))
        self.setTransformationAnchor(QtGui.QGraphicsView.AnchorUnderMouse)
        self.setDragMode(QtGui.QGraphicsView.ScrollHandDrag)

        # Prepare background check-board pattern.
        # tilePixmap = QtGui.QPixmap(64, 64)
        # tilePixmap.fill(QtCore.Qt.white)
        # tilePainter = QtGui.QPainter(tilePixmap)
        # color = QtGui.QColor(220, 220, 220)
        # tilePainter.fillRect(0, 0, 32, 32, color)
        # tilePainter.fillRect(32, 32, 32, 32, color)
        # tilePainter.end()

        tilePixmap = QtGui.QPixmap(30, 30)
        tilePixmap.fill(QtCore.Qt.white)
        self.setBackgroundBrush(QtGui.QBrush(tilePixmap))

    def drawBackground(self, p, rect):
        p.save()
        p.resetTransform()
        p.drawTiledPixmap(self.viewport().rect(),
                self.backgroundBrush().texture())
        p.restore()

    def openFile(self, svg_file):
        if not svg_file.exists():
            return

        s = self.scene()

        #Reset the zoom factor
        self.factor = 1
        #Reset the car
        s.car = None
        #Recreate a map tree by parsing the SVG
        s.map = svg.SvgTree(svg_file.fileName())

        if self.backgroundItem:
            drawBackground = self.backgroundItem.isVisible()
        else:
            drawBackground = False

        if self.outlineItem:
            drawOutline = self.outlineItem.isVisible()
        else:
            drawOutline = True

        s.clear()
        self.resetTransform

        # View containg the SVG map
        self.svgItem = QtSvg.QGraphicsSvgItem(svg_file.fileName())
        self.svgItem.setFlags(QtGui.QGraphicsItem.ItemClipsToShape)
        self.svgItem.setCacheMode(QtGui.QGraphicsItem.NoCache)
        self.svgItem.setZValue(0)


        # Background (defualt : plain white)
        self.backgroundItem = QtGui.QGraphicsRectItem(self.svgItem.boundingRect())
        self.backgroundItem.setBrush(QtCore.Qt.white)
        self.backgroundItem.setPen(QtGui.QPen())
        self.backgroundItem.setVisible(drawBackground)
        self.backgroundItem.setZValue(-1)

        # A dashed (outline) of the SVG map
        self.outlineItem = QtGui.QGraphicsRectItem(self.svgItem.boundingRect())
        outline = QtGui.QPen(QtCore.Qt.black, 2, QtCore.Qt.DashDotLine)
        outline.setCosmetic(True)
        self.outlineItem.setPen(outline)
        self.outlineItem.setBrush(QtGui.QBrush(QtCore.Qt.NoBrush))
        self.outlineItem.setVisible(drawOutline)
        self.outlineItem.setZValue(1)

        s.addItem(self.backgroundItem)
        s.addItem(self.svgItem)
        s.addItem(self.outlineItem)

        self.x = 0
        self.y = 0

        self.updateScene()

    def updateScene(self):
        self.scene().setSceneRect(self.outlineItem.boundingRect().adjusted(self.x-10, self.y-10, self.x+10, self.y+10))

    def setRenderer(self, renderer):
        self.renderer = renderer
        self.setViewport(QtGui.QWidget())

    def setViewBackground(self, enable):
        if self.backgroundItem:
            self.backgroundItem.setVisible(enable)

    def setViewOutline(self, enable):
        if self.outlineItem:
            self.outlineItem.setVisible(enable)

    def paintEvent(self, event):
        super(SvgView, self).paintEvent(event)

    def wheelEvent(self, event):
        factor = 1.2**(event.delta() / 240.0)

        self.scaleScene(factor)

        event.accept()

    def scaleScene(self, factor):
        self.factor *= factor
        self.scale(factor, factor)
        # self.svgItem.scale(factor, factor)
        # self.outlineItem.scale(factor, factor)
        # self.backgroundItem.scale(factor, factor)


if __name__ == '__main__':

    import sys

    app = QtGui.QApplication(sys.argv)

    window = MainWindow()
    if len(sys.argv) == 2:
        window.openFile(sys.argv[1])
    else:
        window.openFile('maps/mapexample.svg')
    window.show()
    sys.exit(app.exec_())